server:
  address: 0.0.0.0
  port: 6096

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

email:
  config:
    host:        # QQ邮箱的SMTP服务器地址
    port:                 # SMTP服务器端口，对于QQ邮箱TLS为587
    sender:   # QQ邮箱地址
    password:   # QQ邮箱生成的授权码
    protocol:

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

python:
  service:
    url: http://localhost:5000